### PR TITLE
Extract fragment parsing

### LINKED ISSUE #15: Move parsing of fragments out of the query building
We should able to use fragments in different contexts (like #3), at the moment it is restricted to Queries. This should also allow for doing more complex parsing (like #13). 

I would move to a `FragmentParser` that accepts an array and turns it into a "parsed" array. This way it can easily be re-used in other contexts.

I do see other parsers in the future (like ExceptionParser for extracting error info, or AggregationParser for simplifying aggregation results, ...). So adding a namespace `Parsers` sounds logical. We can move the ResultParsers under this.

### PR DESCRIPTION
**Pull request by dieterve**
Not really sure about the creating of an `FragmentParser` instance in the `AbstractQuery` constructor, but there is no way to really inject it. I could also use a `parseFragmentsWith` so it can be overwritten (for tests for example), but there isn't a real life use case for opening it up the outside world.

Also tried to find a common ground for the `FragmentParser` and the `ArrayResultsParser` but they are so different in context that it doesn't help either of them to follow an interface.

Closes #15

### CODE REVIEW

**Comment by bramdevries** [comment]
:+1:

File: src/Abstracts/AbstractQuery.php [hunk 1]
```diff
@@ -154,37 +161,21 @@ protected function buildQuery()
...
-	 * Traverses the body and checks if there are any abstracts (filters, queries) to be replaced with their
-	 * body.
+	 * Replace fragments with their body.
 	 *
 	 * @param array $body
 	 *
 	 * @return array
 	 */
-	protected function parseAbstracts(array $body)
+	protected function parseFragments(array $body)
```
Comment (Anahkiasen) [inline src/Abstracts/AbstractQuery.php]: Does this even still need to be a separate method?

**Comment by Anahkiasen** [comment]
On a related note this is something I wonder every time, should ElasticSearcher come with built-in fragments for common filters/queries?

File: src/Abstracts/AbstractQuery.php (hunk 1 above)
Comment (dieterve) [inline src/Abstracts/AbstractQuery.php]: Hmm, good point.

**Comment by dieterve** [comment]
The idea is to have a set of common filters/queries/analyzers/..., yes. Its primary goal is to abstract fragments of a query to re-occur a lot. Inside a project that might also be a `PublishedBooksFragment`, which scopes a query to only published books, for example.

**Comment by Anahkiasen** [comment]
I do have such fragments in the apps I use ESer in, but most of the time the fragments I wish I had are just basic ES stuff as it's always hard to remember the structure of filter X or query Y (fields that sometimes do the same thing bear different names, etc)

**Comment by dieterve** [comment]
> I do have such fragments in the apps I use ESer in, but most of the time the fragments I wish I had are just basic ES stuff as it's always hard to remember the structure of filter X or query Y (fields that sometimes do the same thing bear different names, etc)

PRwithlove
